src/Web/Otus.Teaching.Pcf.WebRazor/Models/Giving/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Otus.Teaching.Pcf.WebRazor.Models.Giving
{
    public class Customer
    {
        public Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public List<Preference> Preferences { get; set; }
        public List<PromoCodeShort> PromoCodes { get; set; }
    }

    public class CustomerShort
    {
        public Guid Id { get; set; }

        [Display(Name = "Имя")]
        public string FirstName { get; set; }

        [Display(Name = "Фамилия")]
        public string LastName { get; set; }

        [Display(Name = "Почта")]
        public string Email { get; set; }
    }
}

src/Web/Otus.Teaching.Pcf.WebRazor/Pages/Customers/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Mapster;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Otus.Teaching.Pcf.WebRazor.Models.Giving;
using Otus.Teaching.Pcf.WebRazor.Services.Abstractions;

namespace Otus.Teaching.Pcf.WebRazor.Pages.Customers
{
    public class CreateModel : PageModel
    {
        private readonly IGivingToCustomerService _givingService;

        public CreateModel(IGivingToCustomerService givingService)
        {
            _givingService = givingService;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public List<SelectListItem> ListItems { get; set; }

        public async Task OnGetAsync()
        {
            var preferences = await _givingService.GetAllPreferences();

            ListItems = preferences
                .Select(preference => new SelectListItem
                {
                    Value = preference.Id.ToString(),
                    Text = preference.Name
                }).ToList();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var request = Input.Adapt<CreateOrEditCustomerRequest>();
            request.PreferenceIds = Input.SelectedValues.Select(Guid.Parse).ToList();
            await _givingService.CreateCustomerAsync(request);

            return RedirectToPage(nameof(Index));
        }


        public class InputModel
        {
            [Required]
            [Display(Name = "Имя")]
            public string FirstName { get; set; }

            [Required]
            [Display(Name = "Имя")]
            public string LastName { get; set; }

            [Required]
            [EmailAddress]
            [Display(Name = "Адрес электронной почты")]
            public string Email { get; set; }

            public IEnumerable<string> SelectedValues { get; set; }= new List<string>();
        }
    }
}

src/Web/Otus.Teaching.Pcf.WebRazor/Pages/Customers/Details.cshtml.cs
using System;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Otus.Teaching.Pcf.WebRazor.Models;
using Otus.Teaching.Pcf.WebRazor.Models.Giving;
using Otus.Teaching.Pcf.WebRazor.Services;
using Otus.Teaching.Pcf.WebRazor.Services.Abstractions;

namespace Otus.Teaching.Pcf.WebRazor.Pages.Customers
{
    public class Details : PageModel
    {
        private readonly IGivingToCustomerService _givingService;

        public Details(IGivingToCustomerService givingService)
        {
            _givingService = givingService;
        }

        public Customer Customer { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid id)
        {
            Customer = await _givingService.GetCustomerAsync(id);
            return Page();
        }
    }
}

src/Web/Otus.Teaching.Pcf.WebRazor/Pages/Customers/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Mapster;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Otus.Teaching.Pcf.WebRazor.Models.Giving;
using Otus.Teaching.Pcf.WebRazor.Services.Abstractions;

namespace Otus.Teaching.Pcf.WebRazor.Pages.Customers
{
    public class EditModel : PageModel
    {
        private readonly IGivingToCustomerService _givingService;

        public EditModel(IGivingToCustomerService givingService)
        {
            _givingService = givingService;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public List<SelectListItem> ListItems { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid id)
        {
            var customer = await _givingService.GetCustomerAsync(id);
            Input = customer.Adapt<InputModel>();

            var preferences = await _givingService.GetAllPreferences();
            var ids = customer.Preferences.Select(p => p.Id);
            ListItems = preferences
                .Select(preference => new SelectListItem
                {
                    Value = preference.Id.ToString(),
                    Text = preference.Name,
                    Selected = ids.Contains(preference.Id)
                }).ToList();

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Guid id)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var request = Input.Adapt<CreateOrEditCustomerRequest>();
            request.PreferenceIds = Input.SelectedValues.Select(Guid.Parse).ToList();
            await _givingService.UpdateCustomerAsync(id, request);

            return RedirectToPage(nameof(Index));
        }

        public class InputModel
        {
            [Required]
            public Guid Id { get; set; }

            [Required]
            [Display(Name = "Имя")]
            public string FirstName { get; set; }

            [Required]
            [Display(Name = "Имя")]
            public string LastName { get; set; }

            [Required]
            [EmailAddress]
            [Display(Name = "Адрес электронной почты")]
            public string Email { get; set; }

            public IEnumerable<string> SelectedValues { get; set; }
        }
    }
}

src/Web/Otus.Teaching.Pcf.WebRazor/Pages/Customers/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Otus.Teaching.Pcf.WebRazor.Models;
using Otus.Teaching.Pcf.WebRazor.Models.Giving;
using Otus.Teaching.Pcf.WebRazor.Services;
using Otus.Teaching.Pcf.WebRazor.Services.Abstractions;

namespace Otus.Teaching.Pcf.WebRazor.Pages.Customers
{
    public class Index : PageModel
    {
        private readonly IGivingToCustomerService _givingService;

        public Index(IGivingToCustomerService givingService)
        {
            _givingService = givingService;
        }

        public List<CustomerShort> Customers { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            Customers = await _givingService.GetAllAsync();
            return Page();
        }

        public async Task<IActionResult> OnPostDeleteAsync(Guid id)
        {
            await _givingService.DeleteCustomerAsync(id);
            return RedirectToPage();
        }
    }
}

src/Web/Otus.Teaching.Pcf.WebRazor/Pages/Promocodes/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Mapster;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Otus.Teaching.Pcf.WebRazor.Models.Receiving;
using Otus.Teaching.Pcf.WebRazor.Services.Abstractions;

namespace Otus.Teaching.Pcf.WebRazor.Pages.Promocodes
{
    public class Create : PageModel
    {
        private readonly IReceivingFromPartnerService _receivingFromPartnerService;

        public Create(IReceivingFromPartnerService receivingFromPartnerService)
        {
            _receivingFromPartnerService = receivingFromPartnerService;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public List<SelectListItem> ListItems { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            var preferences = await _receivingFromPartnerService.GetPreferencesAsync();

            ListItems = preferences
                .Select(preference => new SelectListItem
                {
                    Value = preference.Id.ToString(),
                    Text = preference.Name
                }).ToList();

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Guid partnerId)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var request = Input.Adapt<ReceivePromocodeRequest>();
            await _receivingFromPartnerService.ReceivePromoCodeFromPartnerWithPreferenceAsync(partnerId, request);

            return RedirectToPage(nameof(Index));
        }

        public class InputModel
        {
            [Required]
            public string ServiceInfo { get; set; }

            [Required]
            public string PromoCode { get; set; }

            [Required]
            public Guid PreferenceId { get; set; }

            public Guid? PartnerManagerId { get; set; }

        }
    }
}

src/Web/Otus.Teaching.Pcf.WebRazor/Pages/Customers/Create.cshtml
@page
@model Otus.Teaching.Pcf.WebRazor.Pages.Customers.CreateModel

@{
    ViewData["Title"] = "Создание покупателя";
}

<h3>Создать нового покупателя</h3>

<form method="post">
    <div class="form-group">
        <label asp-for="Input.FirstName"></label>
        <input class="form-control" asp-for="Input.FirstName"/>
        <span asp-validation-for="Input.FirstName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Input.LastName"></label>
        <input class="form-control" asp-for="Input.LastName"/>
        <span asp-validation-for="Input.LastName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Input.Email"></label>
        <input class="form-control" asp-for="Input.Email"/>
        <span asp-validation-for="Input.Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Input.SelectedValues">Выберите предпочтения</label>
        <select class="form-control " asp-for="Input.SelectedValues" asp-items="Model.ListItems"></select>
        <span asp-validation-for="Input.SelectedValues" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Создать</button>
</form>

src/Web/Otus.Teaching.Pcf.WebRazor/Pages/Customers/Details.cshtml
@page "{id}"
@model Otus.Teaching.Pcf.WebRazor.Pages.Customers.Details


<h3>Предпочтения</h3>

<h4>@Model.Customer.FirstName @Model.Customer.LastName (@Model.Customer.Email) </h4>
<div>
    <table class="table table-borderless table-striped">
        <tbody>
        @foreach (var pref in Model.Customer.Preferences)
        {
            <tr>
                <td class="text-left">@pref.Id</td>
                <td class="text-left"> @pref.Name</td>
            </tr>
        }
        </tbody>
    </table>

</div>

src/Web/Otus.Teaching.Pcf.WebRazor/Pages/Customers/Edit.cshtml
@page "{id}"
@model Otus.Teaching.Pcf.WebRazor.Pages.Customers.EditModel

@{
    ViewData["Title"] = "Изменить покупателя";
}

<h3>Изменить данные покупателя</h3>

<form asp-action="SaveUser">
    <div class="form-group">
        <label asp-for="Input.FirstName"></label>
        <input class="form-control" asp-for="Input.FirstName" />
        <span asp-validation-for="Input.FirstName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Input.LastName"></label>
        <input class="form-control" asp-for="Input.LastName" />
        <span asp-validation-for="Input.LastName"  class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Input.Email"></label>
        <input class="form-control" asp-for="Input.Email" />
        <span asp-validation-for="Input.Email"  class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Input.SelectedValues">Отредактируйте предпочтения</label>
        <select class="form-control" asp-for="Input.SelectedValues" asp-items="Model.ListItems"></select>
        <span asp-validation-for="Input.SelectedValues" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

src/Web/Otus.Teaching.Pcf.WebRazor/Pages/Customers/Index.cshtml
@page
@model Customers.Index

@{
    ViewData["Title"] = "Customers";
}

<h3>Покупатели</h3>
<div class="m-2">
    <a class="btn btn-primary" asp-page="Create">Создать покупателя</a>
</div>
<div class="m-2">
    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>ID</th>
            <th>Электронная почта</th>
            <th>Имя</th>
            <th>Фамилия</th>
            <th>Действия</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var customer in Model.Customers)
        {
            <tr>
                <td>@customer.Id</td>
                <td>@customer.Email</td>
                <td>@customer.FirstName</td>
                <td>@customer.LastName</td>
                <td>
                    <div class="btn-group-sm text-center">
                        <a class="btn btn-info" asp-page="Details" asp-route-id="@customer.Id">Подробно</a>
                        <a class="btn btn-info" asp-page="Edit" asp-route-id="@customer.Id">Редактировать</a>
                        <form class="text-center" asp-page-handler="Delete">
                            <input type="hidden" name="id" value="@customer.Id"/>
                            <button type="submit" class="btn btn-sm btn-danger m-1">
                                Удалить
                            </button>
                        </form>
                    </div>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>